---
openapi: 3.0.0
info:
  title: Audit API
  description: This API receives input from front end website where users input the stock number
  version: 1.0.0
  contact:
    email: mhsiao6@my.bcit.ca
paths:
  /health:
    get:
      operationId: app.health
      responses:
        '200':
          description: service is running.
  /stockNumber:
    get: 
      tags: 
        - investors 
      summary: gets new stock number infos 
      operationId: app.get_stock_number_Q
      description: Gets stock number infos from history
      parameters: 
        - name: index
          in: query 
          description: gets the info at the index in the event store
          schema: 
            type: integer
            example: 3
      responses: 
        '200': 
          description: Successfully returned a stock number infos
          content: 
            application/json: 
              schema: 
                type: object 
                items: 
                  $ref: '#/components/schemas/stockNumber' 
        '400': 
          description: Invalid request 
          content: 
            application/json: 
              schema: 
                type: object 
                properties: 
                  message: 
                    type: string
        '404': 
          description: Not Found 
          content: 
            application/json: 
              schema: 
                type: object 
                properties: 
                  message: 
                    type: string
  /dateRange:
    get: 
      tags: 
        - investors 
      summary: gets new date range 
      operationId: app.get_date_range_Q
      description: Gets a time frame from history
      parameters: 
        - name: index
          in: query 
          description: gets the info at the index in the event store 
          schema: 
            type: integer
            example: 3
      responses: 
        '200': 
          description: Successfully returned a date ranges
          content: 
            application/json: 
              schema: 
                type: object
                items: 
                  $ref: '#/components/schemas/dateRange' 
        '400': 
          description: Invalid request 
          content: 
            application/json: 
              schema: 
                type: object 
                properties: 
                  message: 
                    type: string
        '404': 
          description: Not Found 
          content: 
            application/json: 
              schema: 
                type: object 
                properties: 
                  message: 
                    type: string
components:
  schemas:
    stockNumber:
      required:
      - investor_ID
      - price_Date
      - stock_Name
      - stock_Number
      - stock_Price
      - trace_id
      type: object
      properties:
        investor_ID:
          type: string
          format: uuid
          example: d290f1ee-6c54-4b01-90e6-d701748f0851
        stock_Number:
          type: string
          example: AAPL
        stock_Name:
          type: string
          example: Apple Inc
        price_Date:
          type: string
          format: date-time
          example: "2020-08-29T09:12:33.001Z"
        stock_Price:
          type: number
          example: 200
        trace_id:
          type: string
          example: ""
    dateRange:
      required:
      - day
      - investor_ID
      - month
      - time
      - year
      - trace_id
      properties:
        investor_ID:
          type: string
          format: uuid
          example: d290f1ee-6c54-4b01-90e6-d701748f0851
        year:
          type: string
          format: year
          example: "2020"
        month:
          type: string
          format: month
          example: Jan
        day:
          type: number
          example: 25
        time:
          type: string
          format: time
          example: "12:20:00"
        trace_id:
          type: string
          example: ""
        